---
- name: Put custom cluster.yml in place
  template:
    src: cluster.yml
    dest: /etc/ood/config/apps/bc_desktop/{{ cluster_name }}.yml
    backup: yes

- name: Put submit.yml.erb in place
  copy:
    src: vnc-submit.yml.erb
    dest: /etc/ood/config/apps/bc_desktop/submit/submit.yml.erb
    backup: yes

- name: Put noVNC.html.erb in place
  copy:
    src: custom-novnc.html.erb
    dest: /var/www/ood/apps/sys/dashboard/app/views/batch_connect/sessions/connections/_novnc.html.erb
    backup: yes

- name: Put form.js in place
  copy:
    src: form.js
    dest: /var/www/ood/apps/sys/bc_desktop/form.js
